### ISSUE TITLE
Limited numbers of customers for a stream

### ISSUE THREAD

**Issue by NanNguyen01** [centricular/webrtcsink#108] opened 2022-10-06 10:12 UTC
i tried 2 version of your code. 
firstly, i used code in main branch. I did the same as your tutorial, and then i opened the web, i clicked many times (maybe 6-10 times) on stream's peer-id, and the problem appeared like the below picture,

![Screenshot from 2022-10-06 16-56-04](https://user-images.githubusercontent.com/101386916/194284978-7650ea2d-e109-4180-ac03-bb42140a7e0e.png)

some consumers is black. 

secondly, i used code in fix-multiple-vpenc. i did and clicked the same i did in the first example and it can load more consumers (maybe 30) and then consumers after that still get black like the picture.

can you explain what happen? How can i solve the problem?

**Comment by MathieuDuponchelle** [comment] 2022-10-06 11:43
`fix-multiple-vpenc` is merged in `main`, if you get different results it's probably because you're using an older version of the code altogether. What video encoder is getting used here?

**Comment by NanNguyen01** [comment] 2022-10-06 12:13
oke, let me check the version of fix-muliple-vpenc. i am using videotestsrc in your example, and i check it uses VP8 coder.

**Comment by NanNguyen01** [comment] 2022-10-07 02:28
i have already pulled the new code. Btw, you can check in main branch if it happen like the picture.
Pls, help me, thanks.

**Comment by MathieuDuponchelle** [comment] 2022-10-07 19:08
@NanNguyen01 please give a try at latest `main` and report :)

**Closed** 2022-10-07 19:08 UTC

**Comment by MathieuDuponchelle** [comment] 2022-10-07 19:16
![Screenshot from 2022-10-07 21-15-36](https://user-images.githubusercontent.com/1278273/194637595-acd691c8-d574-4ef9-b680-667a21ef0692.png)

**Comment by NanNguyen01** [comment] 2022-10-10 04:32
Thanks you.
But, when i closed the web, my stream is died with bug
![Screenshot from 2022-10-10 11-26-43](https://user-images.githubusercontent.com/101386916/194799283-1fbcdec1-2313-4ca7-8081-f14c798b112a.png)

and new problem is when i clicked to open new window, my CPU is increase, and when i opened about 70 windows, the next window is still black and CPU is full. can you explain it ??

**Comment by MathieuDuponchelle** [comment] 2022-10-10 13:50
@thiblahute I believe this first one is for you, though @NanNguyen01 you should open a separate issue (with better description of how to reproduce the bug) if you want to maximize your chances that someone looks at your problem.

Regarding CPU usage, you're aware that `webrtcsink` instantiates one encoder per consumer right? As such it is expected that CPU usage increases linearly along with the number of consumers. That your machine starts to struggle once you reach full CPU usage seems fair enough and not something I am interested in "debugging" to be honest :)
