### ISSUE TITLE
Making the default signaller work over tls

### ISSUE THREAD

**Issue by Hejsil** [centricular/webrtcsink#16] opened 2022-01-11 15:06 UTC
Hello. The default Signaller seems to mostly provide what we need, except the ability to work over tls. I'd be happy to implement this myself and make a PR, but I'm unsure of the exact API for this.

See also https://github.com/centricular/webrtcsink-custom-signaller/issues/1 where I opened this issue on the wrong repo.

**Comment by MathieuDuponchelle** [comment] 2022-01-12 01:13
reposting my answer here too :)

Making the default signaller work over tls is definitely desirable, I'll be happy to review a PR.

The SignallableObject interface was designed with passing properties in mind fwiw: webrtcsink implements the GstChildProxy interface, which means the signaller object can be configured through it, for instance with gst-launch the address can be passed with: gst-launch-1.0 webrtcsink signaller::address="ws://127.0.0.1:8443".

@sdroege do you have advice regarding what the API should look like on the signaller object to enable tls?

**Comment by machenmusik** [comment] 2022-02-08 17:32
Does it not just work if you give it a secure websocket address e.g. wss://my.secure.host.here:port/path ?

Hosting secure localhost servers is a PITA and generally requires manual self-signed certificate acceptance in browser, which is probably why the default is insecure localhost.

**Comment by machenmusik** [comment] 2022-02-10 17:23
FYI, it looks like wss "just works" e.g. `wss://my.secure.host.here:port`
but the code doesn't currently support path (websocket endpoints that are not at root)

**Comment by MathieuDuponchelle** [comment] 2022-03-17 17:34
I have reimplemented the signalling server, it does also support tls. I will close this for now, @machenmusik regarding your point about self-signed certs, it is indeed a PITA but I stumbled upon https://github.com/FiloSottile/mkcert which solves that problem elegantly, in case that helps :)

**Closed by MathieuDuponchelle** 2022-03-17 17:34 UTC
